### ISSUE TITLE
Fail to report when the code is not current directory

### ISSUE THREAD

**Issue by frostming** [laixintao/tokei-pie#5]
Reproduce:

```pytb
$ tokei -o json /path/to/my_code | tokei-pie
Traceback (most recent call last):
  File "/Users/fming/wkspace/github/tokei-pie-plate/venv/bin/tokei-pie", line 8, in <module>
    sys.exit(main())
  File "/Users/fming/wkspace/github/tokei-pie-plate/venv/lib/python3.10/site-packages/tokei_pie/main.py", line 227, in main
    sectors = read_root(data)
  File "/Users/fming/wkspace/github/tokei-pie-plate/venv/lib/python3.10/site-packages/tokei_pie/main.py", line 197, in read_root
    sectors.extend(read_reports(reports, key))
  File "/Users/fming/wkspace/github/tokei-pie-plate/venv/lib/python3.10/site-packages/tokei_pie/main.py", line 176, in read_reports
    sectors = convert2sectors(tree, dict_reports, parent_id)
  File "/Users/fming/wkspace/github/tokei-pie-plate/venv/lib/python3.10/site-packages/tokei_pie/main.py", line 168, in convert2sectors
    dir2sector(".", dirs, reports, sectors, language)
  File "/Users/fming/wkspace/github/tokei-pie-plate/venv/lib/python3.10/site-packages/tokei_pie/main.py", line 140, in dir2sector
    _blanks, _code, _comments = dir2sector(
  File "/Users/fming/wkspace/github/tokei-pie-plate/venv/lib/python3.10/site-packages/tokei_pie/main.py", line 140, in dir2sector
    _blanks, _code, _comments = dir2sector(
  File "/Users/fming/wkspace/github/tokei-pie-plate/venv/lib/python3.10/site-packages/tokei_pie/main.py", line 140, in dir2sector
    _blanks, _code, _comments = dir2sector(
  [Previous line repeated 1 more time]
  File "/Users/fming/wkspace/github/tokei-pie-plate/venv/lib/python3.10/site-packages/tokei_pie/main.py", line 118, in dir2sector
    stats = reports[item]
KeyError: './lib/python3.10/site-packages/jinja2/compiler.py'
```

There seems to be something wrong with the relative path calculation.

**Comment by laixintao** [comment]
yes it was a bug. but i think it has been fixed(with  @yihong0618 's help)

can you upgrade to latest version then try again? (1.2.0)

**Comment by frostming** [comment]
Awesome, thanks
